# Generated by Django 3.2.8 on 2022-01-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=256)),
                ('LastName', models.CharField(blank=True, max_length=256)),
                ('Email', models.EmailField(blank=True, max_length=256)),
                ('ConfirmNum', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PickUpObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BagPulled', models.BooleanField()),
                ('BagPickedUp', models.BooleanField()),
                ('MissedPickUp', models.BooleanField()),
                ('InvalidConfirmNum', models.BooleanField()),
            ],
        ),
    ]
