# Generated by Django 3.2.10 on 2022-01-17 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextToGoApp', '0002_orderobject_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderobject',
            name='Maxsignup',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='pickupobject',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TextToGoApp.orderobject'),
        ),
        migrations.AlterField(
            model_name='orderobject',
            name='timeslot',
            field=models.IntegerField(choices=[(0, '09:10 – 09:20'), (1, '09:20 – 09:30'), (2, '09:30 – 09:40'), (3, '09:40 – 09:50'), (4, '09:50 – 10:00')], null=True),
        ),
    ]
