# Generated by Django 3.2.10 on 2022-01-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextToGoApp', '0004_orderobject_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderobject',
            old_name='Maxsignup',
            new_name='customers_per_slot',
        ),
    ]
