# Generated by Django 3.2.10 on 2022-01-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TextToGoApp', '0005_rename_maxsignup_orderobject_customers_per_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers_per_slot', models.IntegerField(default=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderobject',
            name='customers_per_slot',
        ),
        migrations.AddField(
            model_name='orderobject',
            name='BagPickedUp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderobject',
            name='BagPulled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderobject',
            name='InvalidConfirmNum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderobject',
            name='MissedPickUp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderobject',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='PickUpObject',
        ),
        migrations.AddField(
            model_name='timeslotobject',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TextToGoApp.orderobject'),
        ),
    ]
