# Generated by Django 3.2.10 on 2022-01-19 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextToGoApp', '0006_auto_20220119_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderobject',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
