# Generated by Django 3.2.10 on 2022-01-21 19:42

import TextToGoApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextToGoApp', '0011_alter_orderobject_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=256)),
                ('LastName', models.CharField(blank=True, max_length=256)),
            ],
            bases=(TextToGoApp.models.SingleInstanceMixin, models.Model),
        ),
    ]
