# Generated by Django 3.2.10 on 2022-01-24 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextToGoApp', '0013_alter_orderobject_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderobject',
            name='timeslot',
        ),
        migrations.AddField(
            model_name='orderobject',
            name='begintime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
