# Generated by Django 3.2.10 on 2022-02-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextToGoApp', '0016_auto_20220211_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderobject',
            name='time',
            field=models.TextField(default='yeet'),
        ),
    ]
